### PR TITLE
Fix #440: various fixes for vm_devbox systemd

### LINKED ISSUE #440: vm_devbox: changes to service file so systemd can manage the service
- [x] remove PrivateTmp (this was causing many problems)
- [x] Type=forking (the vm process forks and stays running after vagrant up exits)
- [x] vagrant reload after setting forwarded_port (need to reload for change to take)
- [x] execStop (needs to be an abspath and needs to be in /srv/vm_devbox_user. Just use a stop script and call it)
- [x] TimeoutStartSec=10min. With Type=forking the timeout is at play

### PR DESCRIPTION
**Pull request by e-carlin**
- remove PrivateTmp this was causing many problems
- Type=forking the vm process forks and stays running after vagrant up exits
- vagrant reload after setting forwarded_port (need to reload for change to take)
- execStop needs to be an abspath and needs to be in /srv/vm_devbox_user. Just use a stop script and call it
- TimeoutStartSec=10min. With Type=forking the timeout is at play

### CODE REVIEW

File: rsconf/package_data/vm_devbox/stop.sh.jinja [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#!/bin/bash
+set -eou pipefail
+
+vm_devbox_main() {
+    cd {{ this.run_d }}
```
Comment (robnagler) [inline rsconf/package_data/vm_devbox/stop.sh.jinja:5]: `cd '{{ this.run_d }}'`

File: rsconf/component/vm_devbox.py [hunk 2]
```diff
@@ -56,6 +57,7 @@ def internal_build_write(self):
         self.install_directory(z.run_d)
         self.install_access(mode="500", owner=z.run_u)
         self.install_resource("vm_devbox/start.sh", host_path=z.start_f)
+        self.install_resource("vm_devbox/start.sh", host_path=z.stop_f)
```
Comment (robnagler) [inline rsconf/component/vm_devbox.py:60]: start.sh > stop.sh

**Review by robnagler — COMMENTED** [review]
A bug and a format.
